// <auto-generated />
using System;
using ClientFlow.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClientFlow.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClientFlow.Domain.Branches.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ReportRecipients")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportTime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Head Office",
                            ReportRecipients = "",
                            ReportTime = "08:00"
                        });
                });

            modelBuilder.Entity("ClientFlow.Domain.Feedback.KioskFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BranchName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<int>("OverallRating")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RespectRating")
                        .HasColumnType("int");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("StartedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("TimeRating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("StaffId");

                    b.ToTable("KioskFeedback");
                });

            modelBuilder.Entity("ClientFlow.Domain.Feedback.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("Staff");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            BranchId = new Guid("00000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Name = "Neo Ramohabi"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            BranchId = new Guid("00000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Name = "Baradi Boikanyo"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            BranchId = new Guid("00000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Name = "Tsepo Chefa"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            BranchId = new Guid("00000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Name = "Mpho Phalafang"
                        });
                });

            modelBuilder.Entity("ClientFlow.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000000"),
                            BranchId = (Guid?)null,
                            Email = "admin@example.com",
                            PasswordHash = "PrP+ZrMeO00Q+nC1ytSccRIpSvauTkdqHEBRVdRaoSE=",
                            Role = 2
                        });
                });

            modelBuilder.Entity("ClientFlow.Domain.Settings.Setting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("40eaf4a3-5d07-4a5b-9c8d-6a2e6e3dc0f1"),
                            Key = "ReportRecipients",
                            Value = ""
                        },
                        new
                        {
                            Id = new Guid("6b7d2f8b-0f6f-4a5e-9f7c-0e8e2d2c9a11"),
                            Key = "BranchName",
                            Value = "Head Office"
                        },
                        new
                        {
                            Id = new Guid("e2c4b8e9-1a3d-4e8f-9c0b-3f2e6d7a9b55"),
                            Key = "ReportTime",
                            Value = "08:00"
                        });
                });

            modelBuilder.Entity("ClientFlow.Domain.Surveys.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ResponseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ValueNumber")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ValueText")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("ResponseId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("ClientFlow.Domain.Surveys.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Required")
                        .HasColumnType("bit");

                    b.Property<Guid?>("SectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SettingsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Key = "phone",
                            Order = 1,
                            Prompt = "Please enter your phone number.",
                            Required = true,
                            SectionId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            SurveyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Type = "phone"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Key = "staff",
                            Order = 2,
                            Prompt = "I was assisted by…",
                            Required = true,
                            SectionId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbc"),
                            SurveyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Type = "radio"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Key = "service",
                            Order = 3,
                            Prompt = "Which Liberty service were you assisted with today?",
                            Required = true,
                            SectionId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbc"),
                            SurveyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Type = "radio"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Key = "satisfaction",
                            Order = 4,
                            Prompt = "How satisfied are you with your recent interaction with Liberty?",
                            Required = true,
                            SectionId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbd"),
                            SurveyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Type = "radio"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Key = "timeliness",
                            Order = 5,
                            Prompt = "Was your query handled within a reasonable time?",
                            Required = true,
                            SectionId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbd"),
                            SurveyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Type = "radio"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Key = "professionalism",
                            Order = 6,
                            Prompt = "Did our staff treat you professionally and with respect?",
                            Required = true,
                            SectionId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbd"),
                            SurveyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Type = "radio"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            Key = "recommend",
                            Order = 7,
                            Prompt = "How likely are you to recommend Liberty to a friend or family member?",
                            Required = true,
                            SectionId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbd"),
                            SurveyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Type = "radio"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            Key = "follow_up",
                            Order = 8,
                            Prompt = "Would you like someone to contact you about your experience?",
                            Required = true,
                            SectionId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbe"),
                            SurveyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Type = "radio"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            Key = "improvement",
                            Order = 9,
                            Prompt = "Please tell us briefly what we could do better.",
                            Required = false,
                            SectionId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbe"),
                            SettingsJson = "{\"placeholder\":\"Your feedback helps us improve.\"}",
                            SurveyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Type = "text"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000a"),
                            Key = "end",
                            Order = 10,
                            Prompt = "Thank you for your feedback! Your input helps us improve our service.",
                            Required = false,
                            SectionId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbf"),
                            SurveyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Type = "message"
                        });
                });

            modelBuilder.Entity("ClientFlow.Domain.Surveys.QuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId", "Order")
                        .IsUnique();

                    b.ToTable("Options");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Label = "Neo Ramohabi",
                            Order = 1,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Value = "neo-ramohabi"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Label = "Baradi Boikanyo",
                            Order = 2,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Value = "baradi-boikanyo"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Label = "Tsepo Chefa",
                            Order = 3,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Value = "tsepo-chefa"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            Label = "Mpho Phalafang",
                            Order = 4,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Value = "mpho-phalafang"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000101"),
                            Label = "Policy enquiry",
                            Order = 1,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Value = "policy-enquiry"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000102"),
                            Label = "Claim",
                            Order = 2,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Value = "claim"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000103"),
                            Label = "New policy application",
                            Order = 3,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Value = "new-policy-application"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000104"),
                            Label = "Payment",
                            Order = 4,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Value = "payment"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000105"),
                            Label = "Amendments/ Policy Changes",
                            Order = 5,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Value = "amendments"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000106"),
                            Label = "Other",
                            Order = 6,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Value = "other"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000201"),
                            Label = "😊 1 = Excellent",
                            Order = 1,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000004"),
                            Value = "1"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000202"),
                            Label = "😃 2 = Good",
                            Order = 2,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000004"),
                            Value = "2"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000203"),
                            Label = "😐 3 = Okay",
                            Order = 3,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000004"),
                            Value = "3"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000204"),
                            Label = "😞 4 = Poor",
                            Order = 4,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000004"),
                            Value = "4"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000205"),
                            Label = "😡 5 = Very Poor",
                            Order = 5,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000004"),
                            Value = "5"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000301"),
                            Label = "Not at all",
                            Order = 1,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000005"),
                            Value = "not-at-all"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000302"),
                            Label = "No",
                            Order = 2,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000005"),
                            Value = "no"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000303"),
                            Label = "Neutral",
                            Order = 3,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000005"),
                            Value = "neutral"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000304"),
                            Label = "Yes, mostly",
                            Order = 4,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000005"),
                            Value = "yes-mostly"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000305"),
                            Label = "Absolutely",
                            Order = 5,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000005"),
                            Value = "absolutely"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000401"),
                            Label = "Not at all",
                            Order = 1,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000006"),
                            Value = "not-at-all"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000402"),
                            Label = "No",
                            Order = 2,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000006"),
                            Value = "no"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000403"),
                            Label = "Neutral",
                            Order = 3,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000006"),
                            Value = "neutral"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000404"),
                            Label = "Yes, mostly",
                            Order = 4,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000006"),
                            Value = "yes-mostly"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000405"),
                            Label = "Absolutely",
                            Order = 5,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000006"),
                            Value = "absolutely"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000501"),
                            Label = "😊 1 = Extremely likely",
                            Order = 1,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000007"),
                            Value = "1"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000502"),
                            Label = "😃 2 = Very likely",
                            Order = 2,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000007"),
                            Value = "2"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000503"),
                            Label = "😐 3 = Neutral",
                            Order = 3,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000007"),
                            Value = "3"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000504"),
                            Label = "😞 4 = Slightly likely",
                            Order = 4,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000007"),
                            Value = "4"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000505"),
                            Label = "😡 5 = Not at all likely",
                            Order = 5,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000007"),
                            Value = "5"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000601"),
                            Label = "Yes",
                            Order = 1,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000008"),
                            Value = "yes"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000602"),
                            Label = "No",
                            Order = 2,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000008"),
                            Value = "no"
                        });
                });

            modelBuilder.Entity("ClientFlow.Domain.Surveys.QuestionRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SourceQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Rules");
                });

            modelBuilder.Entity("ClientFlow.Domain.Surveys.Response", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Channel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Responses");
                });

            modelBuilder.Entity("ClientFlow.Domain.Surveys.ResponseSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetaJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("ClientFlow.Domain.Surveys.Survey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomCss")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ScopedCss")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThemeAccent")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("ThemeJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThemePanel")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Surveys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Code = "liberty-nps",
                            Description = "How likely are you to recommend Liberty?",
                            IsActive = true,
                            ThemeJson = "{\"accent\":\"#de2b2b\"}",
                            Title = "Liberty NPS 2025"
                        });
                });

            modelBuilder.Entity("ClientFlow.Domain.Surveys.SurveySection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Columns")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("SettingsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId");

                    b.ToTable("Sections");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Columns = 1,
                            Order = 1,
                            SurveyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Title = "Client Identification"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbc"),
                            Columns = 1,
                            Order = 2,
                            SurveyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Title = "Service Interaction"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbd"),
                            Columns = 1,
                            Order = 3,
                            SurveyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Title = "Core Satisfaction Questions"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbe"),
                            Columns = 1,
                            Order = 4,
                            SurveyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Title = "Feedback & Follow-Up"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbf"),
                            Columns = 1,
                            Order = 5,
                            SurveyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Title = "End Screen"
                        });
                });

            modelBuilder.Entity("ClientFlow.Domain.Feedback.KioskFeedback", b =>
                {
                    b.HasOne("ClientFlow.Domain.Branches.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClientFlow.Domain.Feedback.Staff", "Staff")
                        .WithMany("Feedback")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("ClientFlow.Domain.Surveys.Answer", b =>
                {
                    b.HasOne("ClientFlow.Domain.Surveys.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClientFlow.Domain.Surveys.Response", "Response")
                        .WithMany("Answers")
                        .HasForeignKey("ResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Response");
                });

            modelBuilder.Entity("ClientFlow.Domain.Surveys.Question", b =>
                {
                    b.HasOne("ClientFlow.Domain.Surveys.Survey", null)
                        .WithMany("Questions")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClientFlow.Domain.Surveys.SurveySection", b =>
                {
                    b.HasOne("ClientFlow.Domain.Surveys.Survey", null)
                        .WithMany("Sections")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClientFlow.Domain.Feedback.Staff", b =>
                {
                    b.HasOne("ClientFlow.Domain.Branches.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Branch");

                    b.Navigation("Feedback");
                });

            modelBuilder.Entity("ClientFlow.Domain.Users.User", b =>
                {
                    b.HasOne("ClientFlow.Domain.Branches.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ClientFlow.Domain.Users.User", "CreatedByUser")
                        .WithMany("CreatedUsers")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Branch");

                    b.Navigation("CreatedByUser");

                    b.Navigation("CreatedUsers");
                });

            modelBuilder.Entity("ClientFlow.Domain.Surveys.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("ClientFlow.Domain.Surveys.Response", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("ClientFlow.Domain.Surveys.Survey", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Sections");
                });
#pragma warning restore 612, 618
        }
    }
}
